### ISSUE TITLE
degauss menu / compose

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/dht#75]
## degauss menu + docker compose

Best way to take state of DeGAUSS app (or copied commands) and prefill into a degauss compose file?  (`dht::use_compose_file()`)  Use a package vignette to demonstrate this?

- how to merge these output files into one file at the end of a pipeline?
- how to run in series? (and dissaggregate output logs)
- how to clean up and rm containers when done automatically?

#### advantages

- errors complete pipeline if one step fails (and notifies you of which one)
- can run geomarker containers in parallel
- can manage runtime resources; e.g. 
```yaml
deploy:
  resources:
    reservations:
      memory: 20gb
```

Example working degauss compose file (`compose.yaml`):

```yaml
x-defaults:
  volumes: &volume
    - ${PWD}:/tmp
  depends_on: &depends
    geocoder:
      condition: service_completed_successfully

services:
  geocoder:
    image: ghcr.io/degauss-org/geocoder:3.2.0
    command: ${ADDRESS_FILE:-address.csv} 0.5
    volumes: *volume
  st_census_tract:
    image: ghcr.io/degauss-org/st_census_tract:0.2.0
    command: ${GEOCODE_FILE:-address_geocoder_3.2.0_score_threshold_0.5.csv}
    volumes: *volume
    depends_on: *depends
  pm:
    image: ghcr.io/degauss-org/pm:0.2.0
    command: ${GEOCODE_FILE:-address_geocoder_3.2.0_score_threshold_0.5.csv}
    volumes: *volume
    depends_on: *depends
```

This can be called with:

```sh
ADDRESS_FILE=raisa_address.csv docker-compose up
```
Mounting a volume could use the file directly rather than mounting the entire working directory:

```yaml
geocoder_another_way:
  image: ghcr.io/degauss-org/geocoder:3.2.0
  entrypoint: "/app/entrypoint.R input.csv"
  volumes:
    - ./raisa_address.csv:/tmp/input.csv
```

... but, mounting the entire `/tmp` folder allows for saving of the cache, s3_downloads, etc... to make future runs faster
